### PR TITLE
Release strategy

### PR DESCRIPTION
**Pull request by steven-murray**
Adds `setuptools_scm` support, and some GH Actions workflows to auto-release to PyPI when merging to master (if the version is bumped).

Fixes #50

### CODE REVIEW

**Review by mkolopanis — COMMENTED** [review]
I'm a little concerned with the test deploy action. It is set up to run a test-deploy for every push right? I remember bryna discovering with pyuvdata that test-pypi has no sense of self cleaning or removing old versions. So at one point she had to go through and manually delete hundreds of deployments to test-pypi because of some kind of space limitation for repositories.

**Comment by steven-murray** [comment]
@mkolopanis I looked up the issue you mentioned, and found that Bryna had made an excellent issue on it. I think we'll have less trouble because the package size is much smaller. I'm not sure what to do beyond not uploading to the test site at all?

**Comment by mkolopanis** [comment]
I think what ended up happening on pyuvdata was we only do test push to pypi on a version tag. But if you want to do every pr/push we can do that too. up to you!

**Comment by steven-murray** [comment]
The problem is, if you only push on version tags, it only tests at the same time it's going to push it up to the real PyPI, so I'm not sure there's much use

**Review by mkolopanis — APPROVED** [review]
so let it be written!

**Pull request merged**
