### PR TITLE
feat: add systematics_mask parameter

### LINKED ISSUE #36: More general "k mask" for systematics
Could eg. simulate reflection ripples via cable lengths. Should have the ability to apply a general k mask, and some tools to compute specific k masks for certain physical effects.

### PR DESCRIPTION
**Pull request by steven-murray**
Fixes #36 

At least, almost implements it. Simply adds a parameter to the `PowerSpectrum` sensitivity that enables a callable function to set a mask on kperp/kpar. 

Two things might remain:

1. I didn't add documentation to the tutorial notebook. I can do that once #66 is merged since it'll be a conflict. 
2. Setting the `systematics_mask` parameter to a callable is not easy/doable from the YAML config, which essentially renders it useless for CLI usage. We could try to support such usage by employing the `@yaml_func` decorator?
3. Bonus: we could add a few "example" systematics masks functions. But I feel like that might be getting too into the weeds for the actual library.

Suggestions welcome!

### CODE REVIEW

**Comment by mkolopanis** [comment]
now that #66 is merged do you mind adding tutorial?

**Comment by steven-murray** [comment]
@mkolopanis done -- it's in the `getting_started` notebook tutorial, right at the end.

**Comment by mkolopanis** [comment]
I'm having conflicted ideas about the systematics masking on the CLI. Is it really necessary to allow CLI to give systematics masks? Do we expect this to be the main interface with which users interact or do we expect it through a jupyter/ipython notebook?
Full functionality would be nice through any interface, but without unsafe code it might not be possible to allow it through the command line, unless we had like you said a few built in ones they could choose.

**Comment by steven-murray** [comment]
I had the same thoughts on implementing via CLI. I don't like the idea of unsafe evals. It seems like it'd just be too flexible for that interface. Maybe over time we could add a few standard ones (eg. cable reflections), and then these could be handled via CLI. But probably in the meantime we should just allow it from an interpreter.

**Comment by steven-murray** [comment]
@mkolopanis I think this is finally ready

**Review by mkolopanis — APPROVED** [review]
Go go gadget mask!

**Pull request merged**
