### PR TITLE
Ci/GitHub actions

### LINKED ISSUE #24: Move to github actions
Instead of travis

### PR DESCRIPTION
**Pull request by mkolopanis**
set up tests to also run on github actions.
closes #24 
TODO:
- coverage
- Manifest.in ?

### CODE REVIEW

**Comment by mkolopanis** [comment]
using this `tox-gh-actions` separates tests into different gh runners, which helps a little with speed. However now there is an annoying amount of actions. I'm not really tied to using it if you'd prefer to not.

**Review by steven-murray — APPROVED** [review]
Looks reasonable, thanks Matt

**Comment by mkolopanis** [comment]
Looks like pre-commit is having a lot of trouble on windows. but I can't find anything in tox to like conditionally not do pre-commit on windows, or how to fix this issue.

**Comment by steven-murray** [comment]
@mkolopanis I would actually separate the pre-commit stuff from tox altogether -- make it a separate github action.

**Comment by mkolopanis** [comment]
So currently it is run by `tox` as what is called `flake8` do you mean you'd have another action in the tox suite that is just pre-commit. Or a single github action that only runs pre-commit (presumably on a single OS?) for each push/pr?

**Comment by steven-murray** [comment]
Yeah, I'd take the `flake8` out of tox, and add a separate github action just to run pre-commit.

**Comment by mkolopanis** [comment]
Oh I changed the name to remove the reference to "Tox". Looks like you'll have to update the "required checks" since those will never run again.

**Comment by steven-murray** [comment]
🎉

**Pull request merged**
